# This is a basic workflow to help you get started with Actions

name: Check Lint

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x ./HabitTrackerApp/gradlew    
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
          
      - name: Install lint
        run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.49.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/

      - name: Check lint
        run: ktlint -F './HabitTrackerApp/app/src/main/java/com/example/habittrackerapp/**/*.kt' 
        
      - name: Build
        working-directory: ./HabitTrackerApp
        run: ./gradlew  build
